### ISSUE TITLE
How to access member methods?

### ISSUE THREAD

**Issue by jasonknight** [joelkp/scoop#1]
Here is what I have done:

``` c
#ifndef MY_CLASS_H
#define MY_CLASS_H

#include <scoop/BEGIN.h>
#include <scoop/Object.h>

#define MyClass_ \
    int x; \
    int y; \
    int z; 
#define MyClass__ \
    void (*mul)(SCO_TYPE* o,int m);

SCOclass(MyClass);
SCOclassctor(MyClass,sco_MyClass,(SCO_TYPE*o,int sx,int sy,int sz));

#define sco_MyClass_mul(o) \
    (o)->classdesc->vtab.mul(o,m)
void sco_MyClass_mul_(SCO_TYPE *o,int m);
#include <scoop/END.h>

#endif
```

And the C File:

``` c
#define SCO_MODULE MyClass

#include "MyClass.h"
#include <stdio.h>

void sco_MyClass_mul_(SCO_TYPE *o,int m) {
    printf(" %d * %d * %d = %d", o->x,o->y,o->z, (o->x * o->y * o->z * m) );
}
static void MyClass_vtinit(MyClass_CD *o)
{
    MyClass_VT *vt = &o->vtab;
    vt->mul = sco_MyClass_mul_;
}
SCO_CLASSDEF(MyClass, scoNull, 0, MyClass_vtinit);

SCO_CLASSCTOR(MyClass, sco_MyClass, (MyClass *o,int sx,int sy,int sz), (o,sx,sy,sz), o)
{
    o->x = sx;
    o->y = sy;
    o->z = sz;
    return 1;
}
```

My Question is: How can I easily call mul? Do I have to call it direct with sco_MyClass_mul(mc,30) ?

Also, it was working a minute ago, and now I get: `Object-test.c:(.text.startup+0x53): undefined reference to`sco_MyClass_new'`

**Comment by joelkp** [comment]
To answer the main question, mul can be called either as a virtual function or as a normal function (where the normal function call is sco_MyClass_mul_(mc, 30)). Assuming you want it to behave as a virtual function, then yeah, sco_MyClass_mul(mc, 30) does that: in other modules, calling it with an instance pointer of a subtype will work. (Or in the same module if you do a typecast. In any case, such a call with a subtype instance will use the function definition of that subtype: inherited unless overridden by the subtype *_vtinit() function.)

There is of course also a possibly shorter way of calling it: set up a pointer to the vtable (accessing it like the macro does), then using it to call. (You can also use the sco_vtab(o) macro to get the vtab pointer from an object pointer.) Can perhaps be convenient if you call a lot of functions of the exact same class in the same place.

As for the error, I had to make a change to get your code to work. Your macro definition lacked the m parameter:

```
#define sco_MyClass_mul(o) \
    (o)->classdesc->vtab.mul(o,m)
```

Changing this to:

```
#define sco_MyClass_mul(o, m) \
    (o)->classdesc->vtab.mul(o,m)
```

I got it to build when I added a test of MyClass to Object-test.c.

I hope that solves the build issue. If not, from the info you gave, I don't really know what could be wrong. Just in case it may be helpul if a problem remains, here is how I changed the Makefile to add your module. I saved your files in MyClass.h and MyClass.c, and changed the Object-test part of Makefile as follows:

```
Object-test: Object-test.o Object-Thing.o Object-ExtendedThing.o MyClass.o
        $(CC) -o $@ $(LFLAGS) -lscoop \
        Object-test.o Object-Thing.o Object-ExtendedThing.o MyClass.o
```
